version: "3.3"

services:
  ts_vms_app:
    build: .
    container_name: test_rd
    #   - .env
    volumes:
      - .:/usr/src

    command: /bin/bash -x -c "mkdir -p reports; robot -i \"$ROBOT_TAG\" -d ./reports tests;RES=$$?;exit $$RES"
