# run tests manually in the Actions-tab of the project
name: Trigger Tests Manually
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        description: 'Branch for tests to run'
        default: master
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        default: feature1
        required: true
jobs:
    API V3 tests on demand with tag - ${{ github.event.inputs.tag }}:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v2
            with:
              ref: ${{ github.event.inputs.branch }}
        - name: Build docker images
          run: docker-compose up -d
        - name: Run tests
          run: ROBOT_TAG=${{ github.event.inputs.tag }} docker-compose up
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports