name: Trigger Tests Manually
on:
  workflow_dispatch:
  # Dynamic variables
    inputs:
      branch:
        description: 'Branch for tests to run'
        default: master
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        default: feature1
        required: true
jobs:
    API_V3_tests_on_demand:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            ref: ${{ github.event.inputs.branch }}
        # Build and run Robot Framework tests inside Docker container with tags
        - name: Run tests
          run: ROBOT_TAG=${{ github.event.inputs.tag }} docker-compose up --build --exit-code-from ts_vms_app
        # Upload test reports as a zip file
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
        # Path to Robot Framework results reports
            path: ${{ github.workspace }}/reports